""" iso 639 and 639-2 dictionary """

def iso639(code, codeOnly=False):
    """
    iso639 dictionary for language iso639 and 639-2 given one code return the
           other code if exists not all 639-2 have a 639

    Args:
        code (str): language code

    Returns:
        list: list with language code and name in english
    """

    iso639dict = {
        "aa": ["aar", "Afar"],
        "aar": ["aa", "Afar"],
        "ab": ["abk", "Abkhazian"],
        "abk": ["ab", "Abkhazian"],
        "ace": ["", "Achinese"],
        "ach": ["", "Acoli"],
        "ada": ["", "Adangme"],
        "ady": ["", "Adyghe; Adygei"],
        "ae": ["ave", "Avestan"],
        "af": ["afr", "Afrikaans"],
        "afa": ["", "Afro-Asiatic languages"],
        "afh": ["", "Afrihili"],
        "afr": ["af", "Afrikaans"],
        "ain": ["", "Ainu"],
        "ak": ["aka", "Akan"],
        "aka": ["ak", "Akan"],
        "akk": ["", "Akkadian"],
        "alb": ["sq", "Albanian"],
        "ale": ["", "Aleut"],
        "alg": ["", "Algonquian languages"],
        "alt": ["", "Southern Altai"],
        "am": ["amh", "Amharic"],
        "amh": ["am", "Amharic"],
        "an": ["arg", "Aragonese"],
        "ang": ["", "English, Old (ca.450-1100)"],
        "anp": ["", "Angika"],
        "apa": ["", "Apache languages"],
        "ar": ["ara", "Arabic"],
        "ara": ["ar", "Arabic"],
        "arc": ["", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"],
        "arg": ["an", "Aragonese"],
        "arm": ["hy", "Armenian"],
        "arn": ["", "Mapudungun; Mapuche"],
        "arp": ["", "Arapaho"],
        "art": ["", "Artificial languages"],
        "arw": ["", "Arawak"],
        "as": ["asm", "Assamese"],
        "asm": ["as", "Assamese"],
        "ast": ["", "Asturian; Bable; Leonese; Asturleonese"],
        "ath": ["", "Athapascan languages"],
        "aus": ["", "Australian languages"],
        "av": ["ava", "Avaric"],
        "ava": ["av", "Avaric"],
        "ave": ["ae", "Avestan"],
        "awa": ["", "Awadhi"],
        "ay": ["aym", "Aymara"],
        "aym": ["ay", "Aymara"],
        "az": ["aze", "Azerbaijani"],
        "aze": ["az", "Azerbaijani"],
        "ba": ["bak", "Bashkir"],
        "bad": ["", "Banda languages"],
        "bai": ["", "Bamileke languages"],
        "bak": ["ba", "Bashkir"],
        "bal": ["", "Baluchi"],
        "bam": ["bm", "Bambara"],
        "ban": ["", "Balinese"],
        "baq": ["eu", "Basque"],
        "bas": ["", "Basa"],
        "bat": ["", "Baltic languages"],
        "be": ["bel", "Belarusian"],
        "bej": ["", "Beja; Bedawiyet"],
        "bel": ["be", "Belarusian"],
        "bem": ["", "Bemba"],
        "ben": ["bn", "Bengali"],
        "ber": ["", "Berber languages"],
        "bg": ["bul", "Bulgarian"],
        "bh": ["bih", "Bihari languages"],
        "bho": ["", "Bhojpuri"],
        "bi": ["bis", "Bislama"],
        "bih": ["bh", "Bihari languages"],
        "bik": ["", "Bikol"],
        "bin": ["", "Bini; Edo"],
        "bis": ["bi", "Bislama"],
        "bla": ["", "Siksika"],
        "bm": ["bam", "Bambara"],
        "bn": ["ben", "Bengali"],
        "bnt": ["", "Bantu languages"],
        "bo": ["tib", "Tibetan"],
        "bos": ["bs", "Bosnian"],
        "br": ["bre", "Breton"],
        "bra": ["", "Braj"],
        "bre": ["br", "Breton"],
        "bs": ["bos", "Bosnian"],
        "btk": ["", "Batak languages"],
        "bua": ["", "Buriat"],
        "bug": ["", "Buginese"],
        "bul": ["bg", "Bulgarian"],
        "bur": ["my", "Burmese"],
        "byn": ["", "Blin; Bilin"],
        "ca": ["cat", "Catalan; Valencian"],
        "cad": ["", "Caddo"],
        "cai": ["", "Central American Indian languages"],
        "car": ["", "Galibi Carib"],
        "cat": ["ca", "Catalan; Valencian"],
        "cau": ["", "Caucasian languages"],
        "ce": ["che", "Chechen"],
        "ceb": ["", "Cebuano"],
        "cel": ["", "Celtic languages"],
        "ch": ["cha", "Chamorro"],
        "cha": ["ch", "Chamorro"],
        "chb": ["", "Chibcha"],
        "che": ["ce", "Chechen"],
        "chg": ["", "Chagatai"],
        "chi": ["zh", "Chinese"],
        "chk": ["", "Chuukese"],
        "chm": ["", "Mari"],
        "chn": ["", "Chinook jargon"],
        "cho": ["", "Choctaw"],
        "chp": ["", "Chipewyan; Dene Suline"],
        "chr": ["", "Cherokee"],
        "chu": [
            "cu",
            "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old "
            "Church Slavonic",
        ],
        "chv": ["cv", "Chuvash"],
        "chy": ["", "Cheyenne"],
        "cmc": ["", "Chamic languages"],
        "cnr": ["", "Montenegrin"],
        "co": ["cos", "Corsican"],
        "cop": ["", "Coptic"],
        "cor": ["kw", "Cornish"],
        "cos": ["co", "Corsican"],
        "cpe": ["", "Creoles and pidgins, English based"],
        "cpf": ["", "Creoles and pidgins, French-based"],
        "cpp": ["", "Creoles and pidgins, Portuguese-based"],
        "cr": ["cre", "Cree"],
        "cre": ["cr", "Cree"],
        "crh": ["", "Crimean Tatar; Crimean Turkish"],
        "crp": ["", "Creoles and pidgins"],
        "cs": ["cze", "Czech"],
        "csb": ["", "Kashubian"],
        "cu": [
            "chu",
            "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old "
            "Church Slavonic",
        ],
        "cus": ["", "Cushitic languages"],
        "cv": ["chv", "Chuvash"],
        "cy": ["wel", "Welsh"],
        "cze": ["cs", "Czech"],
        "da": ["dan", "Danish"],
        "dak": ["", "Dakota"],
        "dan": ["da", "Danish"],
        "dar": ["", "Dargwa"],
        "day": ["", "Land Dayak languages"],
        "de": ["ger", "German"],
        "del": ["", "Delaware"],
        "den": ["", "Slave (Athapascan)"],
        "dgr": ["", "Dogrib"],
        "din": ["", "Dinka"],
        "div": ["dv", "Divehi; Dhivehi; Maldivian"],
        "doi": ["", "Dogri"],
        "dra": ["", "Dravidian languages"],
        "dsb": ["", "Lower Sorbian"],
        "dua": ["", "Duala"],
        "dum": ["", "Dutch, Middle (ca.1050-1350)"],
        "dut": ["nl", "Dutch; Flemish"],
        "dv": ["div", "Divehi; Dhivehi; Maldivian"],
        "dyu": ["", "Dyula"],
        "dz": ["dzo", "Dzongkha"],
        "dzo": ["dz", "Dzongkha"],
        "ee": ["ewe", "Ewe"],
        "efi": ["", "Efik"],
        "egy": ["", "Egyptian (Ancient)"],
        "eka": ["", "Ekajuk"],
        "el": ["gre", "Greek, Modern (1453-)"],
        "elx": ["", "Elamite"],
        "en": ["eng", "English"],
        "eng": ["en", "English"],
        "enm": ["", "English, Middle (1100-1500)"],
        "eo": ["epo", "Esperanto"],
        "epo": ["eo", "Esperanto"],
        "es": ["spa", "Spanish; Castilian"],
        "est": ["et", "Estonian"],
        "et": ["est", "Estonian"],
        "eu": ["baq", "Basque"],
        "ewe": ["ee", "Ewe"],
        "ewo": ["", "Ewondo"],
        "fa": ["per", "Persian"],
        "fan": ["", "Fang"],
        "fao": ["fo", "Faroese"],
        "fat": ["", "Fanti"],
        "ff": ["ful", "Fulah"],
        "fi": ["fin", "Finnish"],
        "fij": ["fj", "Fijian"],
        "fil": ["", "Filipino; Pilipino"],
        "fin": ["fi", "Finnish"],
        "fiu": ["", "Finno-Ugrian languages"],
        "fj": ["fij", "Fijian"],
        "fo": ["fao", "Faroese"],
        "fon": ["", "Fon"],
        "fr": ["fre", "French"],
        "fre": ["fr", "French"],
        "frm": ["", "French, Middle (ca.1400-1600)"],
        "fro": ["", "French, Old (842-ca.1400)"],
        "frr": ["", "Northern Frisian"],
        "frs": ["", "Eastern Frisian"],
        "fry": ["fy", "Western Frisian"],
        "ful": ["ff", "Fulah"],
        "fur": ["", "Friulian"],
        "fy": ["fry", "Western Frisian"],
        "ga": ["gle", "Irish"],
        "gaa": ["", "Ga"],
        "gay": ["", "Gayo"],
        "gba": ["", "Gbaya"],
        "gd": ["gla", "Gaelic; Scottish Gaelic"],
        "gem": ["", "Germanic languages"],
        "geo": ["ka", "Georgian"],
        "ger": ["de", "German"],
        "gez": ["", "Geez"],
        "gil": ["", "Gilbertese"],
        "gl": ["glg", "Galician"],
        "gla": ["gd", "Gaelic; Scottish Gaelic"],
        "gle": ["ga", "Irish"],
        "glg": ["gl", "Galician"],
        "glv": ["gv", "Manx"],
        "gmh": ["", "German, Middle High (ca.1050-1500)"],
        "gn": ["grn", "Guarani"],
        "goh": ["", "German, Old High (ca.750-1050)"],
        "gon": ["", "Gondi"],
        "gor": ["", "Gorontalo"],
        "got": ["", "Gothic"],
        "grb": ["", "Grebo"],
        "grc": ["", "Greek, Ancient (to 1453)"],
        "gre": ["el", "Greek, Modern (1453-)"],
        "grn": ["gn", "Guarani"],
        "gsw": ["", "Swiss German; Alemannic; Alsatian"],
        "gu": ["guj", "Gujarati"],
        "guj": ["gu", "Gujarati"],
        "gv": ["glv", "Manx"],
        "gwi": ["", "Gwich'in"],
        "ha": ["hau", "Hausa"],
        "hai": ["", "Haida"],
        "hat": ["ht", "Haitian; Haitian Creole"],
        "hau": ["ha", "Hausa"],
        "haw": ["", "Hawaiian"],
        "he": ["heb", "Hebrew"],
        "heb": ["he", "Hebrew"],
        "her": ["hz", "Herero"],
        "hi": ["hin", "Hindi"],
        "hil": ["", "Hiligaynon"],
        "him": ["", "Himachali languages; Western Pahari languages"],
        "hin": ["hi", "Hindi"],
        "hit": ["", "Hittite"],
        "hmn": ["", "Hmong; Mong"],
        "hmo": ["ho", "Hiri Motu"],
        "ho": ["hmo", "Hiri Motu"],
        "hr": ["hrv", "Croatian"],
        "hrv": ["hr", "Croatian"],
        "hsb": ["", "Upper Sorbian"],
        "ht": ["hat", "Haitian; Haitian Creole"],
        "hu": ["hun", "Hungarian"],
        "hun": ["hu", "Hungarian"],
        "hup": ["", "Hupa"],
        "hy": ["arm", "Armenian"],
        "hz": ["her", "Herero"],
        "ia": ["ina", "Interlingua (International Auxiliary Language Association)"],
        "iba": ["", "Iban"],
        "ibo": ["ig", "Igbo"],
        "ice": ["is", "Icelandic"],
        "id": ["ind", "Indonesian"],
        "ido": ["io", "Ido"],
        "ie": ["ile", "Interlingue; Occidental"],
        "ig": ["ibo", "Igbo"],
        "ii": ["iii", "Sichuan Yi; Nuosu"],
        "iii": ["ii", "Sichuan Yi; Nuosu"],
        "ijo": ["", "Ijo languages"],
        "ik": ["ipk", "Inupiaq"],
        "iku": ["iu", "Inuktitut"],
        "ile": ["ie", "Interlingue; Occidental"],
        "ilo": ["", "Iloko"],
        "ina": ["ia", "Interlingua (International Auxiliary Language Association)"],
        "inc": ["", "Indic languages"],
        "ind": ["id", "Indonesian"],
        "ine": ["", "Indo-European languages"],
        "inh": ["", "Ingush"],
        "io": ["ido", "Ido"],
        "ipk": ["ik", "Inupiaq"],
        "ira": ["", "Iranian languages"],
        "iro": ["", "Iroquoian languages"],
        "is": ["ice", "Icelandic"],
        "it": ["ita", "Italian"],
        "ita": ["it", "Italian"],
        "iu": ["iku", "Inuktitut"],
        "ja": ["jpn", "Japanese"],
        "jav": ["jv", "Javanese"],
        "jbo": ["", "Lojban"],
        "jpn": ["ja", "Japanese"],
        "jpr": ["", "Judeo-Persian"],
        "jrb": ["", "Judeo-Arabic"],
        "jv": ["jav", "Javanese"],
        "ka": ["geo", "Georgian"],
        "kaa": ["", "Kara-Kalpak"],
        "kab": ["", "Kabyle"],
        "kac": ["", "Kachin; Jingpho"],
        "kal": ["kl", "Kalaallisut; Greenlandic"],
        "kam": ["", "Kamba"],
        "kan": ["kn", "Kannada"],
        "kar": ["", "Karen languages"],
        "kas": ["ks", "Kashmiri"],
        "kau": ["kr", "Kanuri"],
        "kaw": ["", "Kawi"],
        "kaz": ["kk", "Kazakh"],
        "kbd": ["", "Kabardian"],
        "kg": ["kon", "Kongo"],
        "kha": ["", "Khasi"],
        "khi": ["", "Khoisan languages"],
        "khm": ["km", "Central Khmer"],
        "kho": ["", "Khotanese; Sakan"],
        "ki": ["kik", "Kikuyu; Gikuyu"],
        "kik": ["ki", "Kikuyu; Gikuyu"],
        "kin": ["rw", "Kinyarwanda"],
        "kir": ["ky", "Kirghiz; Kyrgyz"],
        "kj": ["kua", "Kuanyama; Kwanyama"],
        "kk": ["kaz", "Kazakh"],
        "kl": ["kal", "Kalaallisut; Greenlandic"],
        "km": ["khm", "Central Khmer"],
        "kmb": ["", "Kimbundu"],
        "kn": ["kan", "Kannada"],
        "ko": ["kor", "Korean"],
        "kok": ["", "Konkani"],
        "kom": ["kv", "Komi"],
        "kon": ["kg", "Kongo"],
        "kor": ["ko", "Korean"],
        "kos": ["", "Kosraean"],
        "kpe": ["", "Kpelle"],
        "kr": ["kau", "Kanuri"],
        "krc": ["", "Karachay-Balkar"],
        "krl": ["", "Karelian"],
        "kro": ["", "Kru languages"],
        "kru": ["", "Kurukh"],
        "ks": ["kas", "Kashmiri"],
        "ku": ["kur", "Kurdish"],
        "kua": ["kj", "Kuanyama; Kwanyama"],
        "kum": ["", "Kumyk"],
        "kur": ["ku", "Kurdish"],
        "kut": ["", "Kutenai"],
        "kv": ["kom", "Komi"],
        "kw": ["cor", "Cornish"],
        "ky": ["kir", "Kirghiz; Kyrgyz"],
        "la": ["lat", "Latin"],
        "lad": ["", "Ladino"],
        "lah": ["", "Lahnda"],
        "lam": ["", "Lamba"],
        "lao": ["lo", "Lao"],
        "lat": ["la", "Latin"],
        "lav": ["lv", "Latvian"],
        "lb": ["ltz", "Luxembourgish; Letzeburgesch"],
        "lez": ["", "Lezghian"],
        "lg": ["lug", "Ganda"],
        "li": ["lim", "Limburgan; Limburger; Limburgish"],
        "lim": ["li", "Limburgan; Limburger; Limburgish"],
        "lin": ["ln", "Lingala"],
        "lit": ["lt", "Lithuanian"],
        "ln": ["lin", "Lingala"],
        "lo": ["lao", "Lao"],
        "lol": ["", "Mongo"],
        "loz": ["", "Lozi"],
        "lt": ["lit", "Lithuanian"],
        "ltz": ["lb", "Luxembourgish; Letzeburgesch"],
        "lu": ["lub", "Luba-Katanga"],
        "lua": ["", "Luba-Lulua"],
        "lub": ["lu", "Luba-Katanga"],
        "lug": ["lg", "Ganda"],
        "lui": ["", "Luiseno"],
        "lun": ["", "Lunda"],
        "luo": ["", "Luo (Kenya and Tanzania)"],
        "lus": ["", "Lushai"],
        "lv": ["lav", "Latvian"],
        "mac": ["mk", "Macedonian"],
        "mad": ["", "Madurese"],
        "mag": ["", "Magahi"],
        "mah": ["mh", "Marshallese"],
        "mai": ["", "Maithili"],
        "mak": ["", "Makasar"],
        "mal": ["ml", "Malayalam"],
        "man": ["", "Mandingo"],
        "mao": ["mi", "Maori"],
        "map": ["", "Austronesian languages"],
        "mar": ["mr", "Marathi"],
        "mas": ["", "Masai"],
        "may": ["ms", "Malay"],
        "mdf": ["", "Moksha"],
        "mdr": ["", "Mandar"],
        "men": ["", "Mende"],
        "mg": ["mlg", "Malagasy"],
        "mga": ["", "Irish, Middle (900-1200)"],
        "mh": ["mah", "Marshallese"],
        "mi": ["mao", "Maori"],
        "mic": ["", "Mi'kmaq; Micmac"],
        "min": ["", "Minangkabau"],
        "mis": ["", "Uncoded languages"],
        "mk": ["mac", "Macedonian"],
        "mkh": ["", "Mon-Khmer languages"],
        "ml": ["mal", "Malayalam"],
        "mlg": ["mg", "Malagasy"],
        "mlt": ["mt", "Maltese"],
        "mn": ["mon", "Mongolian"],
        "mnc": ["", "Manchu"],
        "mni": ["", "Manipuri"],
        "mno": ["", "Manobo languages"],
        "moh": ["", "Mohawk"],
        "mon": ["mn", "Mongolian"],
        "mos": ["", "Mossi"],
        "mr": ["mar", "Marathi"],
        "ms": ["may", "Malay"],
        "mt": ["mlt", "Maltese"],
        "mul": ["", "Multiple languages"],
        "mun": ["", "Munda languages"],
        "mus": ["", "Creek"],
        "mwl": ["", "Mirandese"],
        "mwr": ["", "Marwari"],
        "my": ["bur", "Burmese"],
        "myn": ["", "Mayan languages"],
        "myv": ["", "Erzya"],
        "na": ["nau", "Nauru"],
        "nah": ["", "Nahuatl languages"],
        "nai": ["", "North American Indian languages"],
        "nap": ["", "Neapolitan"],
        "nau": ["na", "Nauru"],
        "nav": ["nv", "Navajo; Navaho"],
        "nb": ["nob", "Bokmål, Norwegian; Norwegian Bokmål"],
        "nbl": ["nr", "Ndebele, South; South Ndebele"],
        "nd": ["nde", "Ndebele, North; North Ndebele"],
        "nde": ["nd", "Ndebele, North; North Ndebele"],
        "ndo": ["ng", "Ndonga"],
        "nds": ["", "Low German; Low Saxon; German, Low; Saxon, Low"],
        "ne": ["nep", "Nepali"],
        "nep": ["ne", "Nepali"],
        "new": ["", "Nepal Bhasa; Newari"],
        "ng": ["ndo", "Ndonga"],
        "nia": ["", "Nias"],
        "nic": ["", "Niger-Kordofanian languages"],
        "niu": ["", "Niuean"],
        "nl": ["dut", "Dutch; Flemish"],
        "nn": ["nno", "Norwegian Nynorsk; Nynorsk, Norwegian"],
        "nno": ["nn", "Norwegian Nynorsk; Nynorsk, Norwegian"],
        "no": ["nor", "Norwegian"],
        "nob": ["nb", "Bokmål, Norwegian; Norwegian Bokmål"],
        "nog": ["", "Nogai"],
        "non": ["", "Norse, Old"],
        "nor": ["no", "Norwegian"],
        "nqo": ["", "N'Ko"],
        "nr": ["nbl", "Ndebele, South; South Ndebele"],
        "nso": ["", "Pedi; Sepedi; Northern Sotho"],
        "nub": ["", "Nubian languages"],
        "nv": ["nav", "Navajo; Navaho"],
        "nwc": ["", "Classical Newari; Old Newari; Classical Nepal Bhasa"],
        "ny": ["nya", "Chichewa; Chewa; Nyanja"],
        "nya": ["ny", "Chichewa; Chewa; Nyanja"],
        "nym": ["", "Nyamwezi"],
        "nyn": ["", "Nyankole"],
        "nyo": ["", "Nyoro"],
        "nzi": ["", "Nzima"],
        "oc": ["oci", "Occitan (post 1500)"],
        "oci": ["oc", "Occitan (post 1500)"],
        "oj": ["oji", "Ojibwa"],
        "oji": ["oj", "Ojibwa"],
        "om": ["orm", "Oromo"],
        "or": ["ori", "Oriya"],
        "ori": ["or", "Oriya"],
        "orm": ["om", "Oromo"],
        "os": ["oss", "Ossetian; Ossetic"],
        "osa": ["", "Osage"],
        "oss": ["os", "Ossetian; Ossetic"],
        "ota": ["", "Turkish, Ottoman (1500-1928)"],
        "oto": ["", "Otomian languages"],
        "pa": ["pan", "Panjabi; Punjabi"],
        "paa": ["", "Papuan languages"],
        "pag": ["", "Pangasinan"],
        "pal": ["", "Pahlavi"],
        "pam": ["", "Pampanga; Kapampangan"],
        "pan": ["pa", "Panjabi; Punjabi"],
        "pap": ["", "Papiamento"],
        "pau": ["", "Palauan"],
        "peo": ["", "Persian, Old (ca.600-400 B.C.)"],
        "per": ["fa", "Persian"],
        "phi": ["", "Philippine languages"],
        "phn": ["", "Phoenician"],
        "pi": ["pli", "Pali"],
        "pl": ["pol", "Polish"],
        "pli": ["pi", "Pali"],
        "pol": ["pl", "Polish"],
        "pon": ["", "Pohnpeian"],
        "por": ["pt", "Portuguese"],
        "pra": ["", "Prakrit languages"],
        "pro": ["", "Provençal, Old (to 1500); Occitan, Old (to 1500)"],
        "ps": ["pus", "Pushto; Pashto"],
        "pt": ["por", "Portuguese"],
        "pus": ["ps", "Pushto; Pashto"],
        "qu": ["que", "Quechua"],
        "que": ["qu", "Quechua"],
        "raj": ["", "Rajasthani"],
        "rap": ["", "Rapanui"],
        "rar": ["", "Rarotongan; Cook Islands Maori"],
        "rm": ["roh", "Romansh"],
        "rn": ["run", "Rundi"],
        "ro": ["rum", "Romanian; Moldavian; Moldovan"],
        "roa": ["", "Romance languages"],
        "roh": ["rm", "Romansh"],
        "rom": ["", "Romany"],
        "ru": ["rus", "Russian"],
        "rum": ["ro", "Romanian; Moldavian; Moldovan"],
        "run": ["rn", "Rundi"],
        "rup": ["", "Aromanian; Arumanian; Macedo-Romanian"],
        "rus": ["ru", "Russian"],
        "rw": ["kin", "Kinyarwanda"],
        "sa": ["san", "Sanskrit"],
        "sad": ["", "Sandawe"],
        "sag": ["sg", "Sango"],
        "sah": ["", "Yakut"],
        "sai": ["", "South American Indian languages"],
        "sal": ["", "Salishan languages"],
        "sam": ["", "Samaritan Aramaic"],
        "san": ["sa", "Sanskrit"],
        "sas": ["", "Sasak"],
        "sat": ["", "Santali"],
        "sc": ["srd", "Sardinian"],
        "scn": ["", "Sicilian"],
        "sco": ["", "Scots"],
        "sd": ["snd", "Sindhi"],
        "se": ["sme", "Northern Sami"],
        "sel": ["", "Selkup"],
        "sem": ["", "Semitic languages"],
        "sg": ["sag", "Sango"],
        "sga": ["", "Irish, Old (to 900)"],
        "sgn": ["", "Sign Languages"],
        "shn": ["", "Shan"],
        "si": ["sin", "Sinhala; Sinhalese"],
        "sid": ["", "Sidamo"],
        "sin": ["si", "Sinhala; Sinhalese"],
        "sio": ["", "Siouan languages"],
        "sit": ["", "Sino-Tibetan languages"],
        "sk": ["slo", "Slovak"],
        "sl": ["slv", "Slovenian"],
        "sla": ["", "Slavic languages"],
        "slo": ["sk", "Slovak"],
        "slv": ["sl", "Slovenian"],
        "sm": ["smo", "Samoan"],
        "sma": ["", "Southern Sami"],
        "sme": ["se", "Northern Sami"],
        "smi": ["", "Sami languages"],
        "smj": ["", "Lule Sami"],
        "smn": ["", "Inari Sami"],
        "smo": ["sm", "Samoan"],
        "sms": ["", "Skolt Sami"],
        "sn": ["sna", "Shona"],
        "sna": ["sn", "Shona"],
        "snd": ["sd", "Sindhi"],
        "snk": ["", "Soninke"],
        "so": ["som", "Somali"],
        "sog": ["", "Sogdian"],
        "som": ["so", "Somali"],
        "son": ["", "Songhai languages"],
        "sot": ["st", "Sotho, Southern"],
        "spa": ["es", "Spanish; Castilian"],
        "sq": ["alb", "Albanian"],
        "sr": ["srp", "Serbian"],
        "srd": ["sc", "Sardinian"],
        "srn": ["", "Sranan Tongo"],
        "srp": ["sr", "Serbian"],
        "srr": ["", "Serer"],
        "ss": ["ssw", "Swati"],
        "ssa": ["", "Nilo-Saharan languages"],
        "ssw": ["ss", "Swati"],
        "st": ["sot", "Sotho, Southern"],
        "su": ["sun", "Sundanese"],
        "suk": ["", "Sukuma"],
        "sun": ["su", "Sundanese"],
        "sus": ["", "Susu"],
        "sux": ["", "Sumerian"],
        "sv": ["swe", "Swedish"],
        "sw": ["swa", "Swahili"],
        "swa": ["sw", "Swahili"],
        "swe": ["sv", "Swedish"],
        "syc": ["", "Classical Syriac"],
        "syr": ["", "Syriac"],
        "ta": ["tam", "Tamil"],
        "tah": ["ty", "Tahitian"],
        "tai": ["", "Tai languages"],
        "tam": ["ta", "Tamil"],
        "tat": ["tt", "Tatar"],
        "te": ["tel", "Telugu"],
        "tel": ["te", "Telugu"],
        "tem": ["", "Timne"],
        "ter": ["", "Tereno"],
        "tet": ["", "Tetum"],
        "tg": ["tgk", "Tajik"],
        "tgk": ["tg", "Tajik"],
        "tgl": ["tl", "Tagalog"],
        "th": ["tha", "Thai"],
        "tha": ["th", "Thai"],
        "ti": ["tir", "Tigrinya"],
        "tib": ["bo", "Tibetan"],
        "tig": ["", "Tigre"],
        "tir": ["ti", "Tigrinya"],
        "tiv": ["", "Tiv"],
        "tk": ["tuk", "Turkmen"],
        "tkl": ["", "Tokelau"],
        "tl": ["tgl", "Tagalog"],
        "tlh": ["", "Klingon; tlhIngan-Hol"],
        "tli": ["", "Tlingit"],
        "tmh": ["", "Tamashek"],
        "tn": ["tsn", "Tswana"],
        "to": ["ton", "Tonga (Tonga Islands)"],
        "tog": ["", "Tonga (Nyasa)"],
        "ton": ["to", "Tonga (Tonga Islands)"],
        "tpi": ["", "Tok Pisin"],
        "tr": ["tur", "Turkish"],
        "ts": ["tso", "Tsonga"],
        "tsi": ["", "Tsimshian"],
        "tsn": ["tn", "Tswana"],
        "tso": ["ts", "Tsonga"],
        "tt": ["tat", "Tatar"],
        "tuk": ["tk", "Turkmen"],
        "tum": ["", "Tumbuka"],
        "tup": ["", "Tupi languages"],
        "tur": ["tr", "Turkish"],
        "tut": ["", "Altaic languages"],
        "tvl": ["", "Tuvalu"],
        "tw": ["twi", "Twi"],
        "twi": ["tw", "Twi"],
        "ty": ["tah", "Tahitian"],
        "tyv": ["", "Tuvinian"],
        "udm": ["", "Udmurt"],
        "ug": ["uig", "Uighur; Uyghur"],
        "uga": ["", "Ugaritic"],
        "uig": ["ug", "Uighur; Uyghur"],
        "uk": ["ukr", "Ukrainian"],
        "ukr": ["uk", "Ukrainian"],
        "umb": ["", "Umbundu"],
        "und": ["", "Undetermined"],
        "ur": ["urd", "Urdu"],
        "urd": ["ur", "Urdu"],
        "uz": ["uzb", "Uzbek"],
        "uzb": ["uz", "Uzbek"],
        "vai": ["", "Vai"],
        "ve": ["ven", "Venda"],
        "ven": ["ve", "Venda"],
        "vi": ["vie", "Vietnamese"],
        "vie": ["vi", "Vietnamese"],
        "vo": ["vol", "Volapük"],
        "vol": ["vo", "Volapük"],
        "vot": ["", "Votic"],
        "wa": ["wln", "Walloon"],
        "wak": ["", "Wakashan languages"],
        "wal": ["", "Wolaitta; Wolaytta"],
        "war": ["", "Waray"],
        "was": ["", "Washo"],
        "wel": ["cy", "Welsh"],
        "wen": ["", "Sorbian languages"],
        "wln": ["wa", "Walloon"],
        "wo": ["wol", "Wolof"],
        "wol": ["wo", "Wolof"],
        "xal": ["", "Kalmyk; Oirat"],
        "xh": ["xho", "Xhosa"],
        "xho": ["xh", "Xhosa"],
        "yao": ["", "Yao"],
        "yap": ["", "Yapese"],
        "yi": ["yid", "Yiddish"],
        "yid": ["yi", "Yiddish"],
        "yo": ["yor", "Yoruba"],
        "yor": ["yo", "Yoruba"],
        "ypk": ["", "Yupik languages"],
        "za": ["zha", "Zhuang; Chuang"],
        "zap": ["", "Zapotec"],
        "zbl": ["", "Blissymbols; Blissymbolics; Bliss"],
        "zen": ["", "Zenaga"],
        "zgh": ["", "Standard Moroccan Tamazight"],
        "zh": ["chi", "Chinese"],
        "zha": ["za", "Zhuang; Chuang"],
        "znd": ["", "Zande languages"],
        "zu": ["zul", "Zulu"],
        "zul": ["zu", "Zulu"],
        "zun": ["", "Zuni"],
        "zxx": ["", "No linguistic content; Not applicable"],
        "zza": ["", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"],
    }

    rc = iso639dict.get(code, None)

    if rc and codeOnly:
        return rc[0]

    return rc
