name: mkvbatchmultiplex # you probably want to 'snapcraft register <name>'
version: '0.9.1b1.dev1' # just for humans, typically '1.2+git' or '1.3.2'
summary: MKVToolNix mkvmerge batch multiplex
description: |
  This app takes a mkbtoolnix-gui generated cli and applies the same commands
  to all the files in the source diretories. 

base: core18

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  mkvbatchmultiplex:
    command: bin/run.sh
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - gsettings
      - home
      - network-bind
      - browser-support
  gsettings:
    command: desktop-launch gsettings
    plugs:
      - gsettings

parts:

  scripts:
    plugin: dump
    source: scripts
    organize:
      'run.sh': bin/
      'mkvmerge': bin/

  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3

  mkvbatchmultiplex:
    # See 'snapcraft plugins'
    after: [desktop-gtk3]
    plugin: python
    python-packages:
      - pymediainfo
      - pyside2
    source: .
    stage-packages:
      - libice-dev
      - libsm6
      - libevdev2
      - libgudev-1.0-0
      - libinput10
      - libdouble-conversion-dev
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libxcb-image0
      - libxcb-icccm4
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - mediainfo
      - libglib2.0-bin
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libxrandr2
      - libasound2
      - libglu1-mesa
      - libgles2-mesa
      - fontconfig
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxi6
      - libegl1
      - libgl1
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - libxslt1.1
      - xfonts-base
      - xfonts-scalable

